cc_library(
    name = "ecs_game",
    include_prefix = "ecs/game",
    hdrs = glob(["**/*.h"]),
    srcs = glob(["**/*.h"]) + glob(["**/*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//source/core:ecs_core"
    ],
)