cc_library(
    name = "SDL",
    include_prefix = "ecs/game",
    hdrs = glob(["**/*.h"]) + glob(["**/*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "@sdl2//:SDL2",
    ],
)